=== Stripping Modules

By default, durexForth boots up with these modules pre-compiled in RAM:

asm:: The assembler. (Required and may not be stripped.)
format:: Numerical formatting words. (Also required.)
wordlist:: Wordlist manipulation. (Required by some modules.)
labels:: Assembler labels.
doloop:: Do-loop words.
sys:: System calls.
debug:: Words for debugging.
ls:: List disk contents.
require:: The words require and required.
v:: The text editor.

To reduce RAM usage, you may make a stripped-down version of durexForth. Do this by following these steps:

. Issue +---modules---+ to unload all modules, or +---editor---+ to unload the editor only.
. One by one, load the modules you want included with your new Forth. (E.g. +include labels+)
. Save the new system with e.g. +save-forth acmeforth+.

=== Custom Start-Up

You may launch a word automatically at start-up by setting the variable +start+ to the execution token of the word.  Example: +' megademo start !+ To save the new configuration to disk, type e.g. +save-forth megademo+.

When writing a new program using a PC text editor, it is practical to configure durexForth to compile and execute the program at startup. That can be set up using the following snippet:

----
$a000 value buf
: go buf s" myprogramfile" buf
loadb buf - evaluate ;
' go start !
save-forth @0:durexforth
----

=== Turn-key Operation

Durexforth offers utilities to save your program in a turn-key fashion by including the +turnkey+ module once the program is ready to be saved.

Programs can be saved in a compacted state using +save-pack+. These programs are stored with 32 bytes between +here+ and +latest+. When they are first loaded, they will restore the header space to its original +top+.

If you have developed a program that has no further need of the interpreter, you can eliminate the dictionary headers entirely when saving with +save-prg+. This allows your program to use memory down to +here+ plus 32 bytes for safety.

After either of these words have saved the file to disk, they will restore forth to the unpacked state, and strip the +turnkey+ module from the dictionary. This allows you to continue to use forth interactively in the case of +save-pack+. As +save-prg+ has stripped the dictionary headers from the system, it will no longer be usable. If you wish to test your program after saving, you can compile a call to +save-prg+ instead:
----
: build save-prg mydemo start @ execute ;
build
----
This will simulate the start-up sequence after saving the packed program.
