=== Music Macro Language

Music Macro Language (MML) has been used since the 1970s to sequence music on computer and video game systems. The MML package is loaded with `include mml`. Two demonstration songs can be found in the `mmldemo` package.

MML songs are played using the Forth word ((play-mml)) which takes three MML strings, one MML melody for each of the three SID voices. An example song is as follows:

----
: frere-jaques
mml" o3l4fgaffgafab->c&c<ab->c&cl8cdc<b-l4af>l8cdc<b-l4affcf&ffcf&f"
mml" r1o3l4fgaffgafab->c&c<ab->c&cl8cdc<b-l4af>l8cdc<b-l4affcf&ffcf&f"
mml" " play-mml ;
----

==== Commands

cdefgab :: The letters `c` to `b` represent musical notes.
Sharp notes are produced by appending a `+`, flat notes are produced by appending a `-`.
The length of a note is specified by appending a number representing its length as a fraction of a whole note.
For example, `c8` represents a C eight note, and `f+2` an F# half note.
Valid note lengths are 1, 2, 3, 4, 6, 8, 16, 24 and 32.
Appending a `.` increases the duration of the note by half of its value.
o :: Followed by a number, `o` selects the octave the instrument will play in.
r :: A rest. The length of the rest is specified in the same manner as the length of a note.
< > :: Used to step down or up one octave.
l :: Followed by a number, specifies the default length used by notes or rests which do not explicitly specify one.
& :: Ties two notes together.
