=== Interpreter

Start up durexForth. When loaded, it will greet you with a blinking yellow cursor, waiting for your input. You have landed in the interpreter!

Let's warm it up a little. Enter +1+ (followed by return). You have now put a digit on the stack. This can be verified by the command +.s+, which will print the stack contents without modifying it. Now enter +.+ to pop the digit and print it to screen, followed by +.s+ to verify that the stack is empty.

Let's define a word +bg!+ for setting the border color...

----
: bg! $d020 c! ;
----

Now try entering +1 bg!+ to change the border color to white.
Then, try changing it back again with +0 bg!+.

=== Introducing the Editor

The v editor is convenient for editing larger pieces of code. With it, you keep an entire source file loaded in RAM, and you can recompile and test it easily.

Start the editor by typing +v+. You will enter the red editor screen. To enter text, first press +i+ to enter insert mode. This mode allows you to insert text into the buffer. You can see that it's active on the +I+ that appears in the lower left corner. This is a good start for creating a program!

Now, enter the following lines...

----
: flash begin 1 $d020 +! again ; flash
----

...and then press &larr; to leave insert mode.
Press _F7_ to compile and run. If everything is entered right, you will be facing a beautiful color cycle.

When you finished watching, press _RESTORE_ to quit your program, then enter +v+ to reopen the editor.

=== Assembler

If you want to color cycle as fast as possible, it is possible to use the durexForth assembler to generate machine code. +code+ and +;code+ define a code word, just like +:+ and +;+ define Forth words. Within a code word, you can use assembler mnemonics.

----
code flash
here ( push current addr )
$d020 inc,
jmp, ( jump to pushed addr )
;code
flash
----

It is also possible to use inline assembly within regular Forth words:

----
: flash begin [ $d020 inc, ] again ;
flash
----

Note: As the +x+ register contains the parameter stack depth, it is important that your assembly code leaves it unchanged.

=== Console I/O Example

This piece of code reads from keyboard and sends back the chars to screen:

----
: foo key emit recurse ;
foo
----

=== Printer Example

This piece of code prints a message to a printer on device #4, and then prints a message to the screen:

----
include io

: print-hello
4 device ( use device 4 )
0 0 47 7 open ioabort ( open address 7 as file 47, abort on failure )
47 chkout ioabort ( redirect output to file 47, abort on failure )
." Hello, printer!" cr
clrchn ( stop input and output redirection )
." Hello, screen!" cr
47 close ( close file 47 ) ;

print-hello
----

The device number and address may differ between printer models. Commodore MPS series printers use address 0 to print in their uppercase/graphics font, and address 7 to print in their lowercase/uppercase font.

=== Avoiding Stack Crashes

Stack overflow and underflow are common causes for errors and crashes.
Simply put, the data stack must not contain too many or too few items.
This section describes some techniques to avoid such errors.

==== Commenting

One helpful technique to avoid stack crashes is to add comments about stack usage.
In this example, we imagine a graphics word "drawbox" that draws a black box.
+( color -- )+ indicates that it takes one argument on stack, and on exit it should
leave nothing on the stack. The comments inside the word (starting with &pound;) indicate what the stack
looks like after the line has executed.

----
: drawbox ( color -- )
10 begin dup 20 < while £ color x
10 begin dup 20 < while £ color x y
2dup £ color x y x y
4 pick £ color x y x y color
blkcol £ color x y
1+ repeat drop £ color x
1+ repeat 2drop ;
----

Once the word is working as supposed, it may be nice to again remove the comments, as
they are no longer very interesting to read.

Note: The Forth standard defines backslash (\) as the line comment character, but the C64 lacks a real backslash. Moreover, ASCII \ and PETSCII &pound; both map to $5c. Therefore, the &pound; character is used as a substitution on the C64.

==== Stack Checks

Another useful technique during development is to check at the end of your main loop
that the stack depth is what you expect it to. This will catch stack underflows
and overflows.

----
: mainloop begin
( do stuff here... )
depth abort" depth not 0"
again ;
----
