=== Stack Manipulation ===

drop ( a -- ):: Drop top of stack.
dup ( a -- a a ):: Duplicate top of stack.
swap ( a b -- b a ):: Swap top stack elements.
over ( a b -- a b a ):: Make a copy of the second item and push it on top.
rot ( a b c -- b c a ):: Rotate the third item to the top.
-rot ( a b c -- c a b ):: rot rot
2drop ( a b -- ):: Drop two topmost stack elements.
2dup ( a b -- a b a b ):: Duplicate two topmost stack elements.
?dup ( a -- a a? ):: Dup a if a differs from 0.
nip ( a b -- b ):: swap drop
tuck ( a b -- b a b ):: dup -rot
pick ( x~u~ ... x~1~ x~0~ u -- x~u~ ... x~1~ x~0~ x~u~ ):: Pick from stack element with depth u to top of stack.
>r ( a -- ):: Move value from top of parameter stack to top of return stack.
r> ( -- a ):: Move value from top of return stack to top of parameter stack.
r@ ( -- a ):: Copy value from top of return stack to top of parameter stack.
depth ( -- n):: +n+ is the number of single-cell values contained in the data stack before +n+ was placed on the stack.
lsb ( -- addr):: The top address of the LSB parameter stack.
msb ( -- addr):: The top address of the MSB parameter stack.
